name: Heartbeat

on:
  schedule:
    # run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call heartbeat function
        env:
          HEARTBEAT_URL: ${{ secrets.HEARTBEAT_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }} # optional; only set if your function requires it
        run: |
          if [ -z "$HEARTBEAT_URL" ]; then
            echo "ERROR: HEARTBEAT_URL secret is not set. Add it in repository Settings → Secrets and variables → Actions."
            exit 1
          fi

          # Try up to 3 times with a short backoff
          max_attempts=3
          attempt=1
          until [ $attempt -gt $max_attempts ]; do
            echo "Attempt $attempt: GET $HEARTBEAT_URL"
            if [ -n "$SUPABASE_ANON_KEY" ]; then
              resp=$(curl -s -o /dev/stderr -w "%{http_code}" -H "apikey: $SUPABASE_ANON_KEY" -H "Authorization: Bearer $SUPABASE_ANON_KEY" --max-time 10 "$HEARTBEAT_URL")
            else
              resp=$(curl -s -o /dev/stderr -w "%{http_code}" --max-time 10 "$HEARTBEAT_URL")
            fi

            if [ "$resp" = "200" ] || [ "$resp" = "204" ]; then
              echo "Heartbeat successful (HTTP $resp)."
              exit 0
            fi

            echo "Heartbeat failed (HTTP $resp). Retrying..."
            attempt=$((attempt+1))
            sleep $((attempt * 2))
          done

          echo "Heartbeat failed after $max_attempts attempts."
          exit 1